1.

In [51]:
import numpy as np
import random

#creating random list method 1
size= []
for i in range(1, 11):
    x = np.random.randint(120, 200)
    size.append(x)
print('size: ', size)

rooms = []
for i in range(1, 11):
    x = np.random.randint(2, 6)
    rooms.append(x)
print('rooms: ', rooms)

price = []
for i in range(1, 11):
    x = np.random.randint(200000, 800000)
    price.append(x)
print('price: ', price)

# #creating random list method 2
# randomsize = random.sample(range(100, 150), 10)
# print(randomsize)

# randomrooms = random.sample(range(1, 11), 10)
# print(randomrooms)


# randomprices = random.sample(range(200000, 800000), 10)
# print(randomprices)

l = size + rooms + price
l = np.array(l)
print('list: ', l)







size:  [166, 176, 130, 187, 127, 132, 128, 177, 152, 163]
rooms:  [5, 4, 5, 2, 2, 3, 4, 3, 3, 4]
price:  [628457, 506601, 692374, 240345, 566213, 248244, 682854, 671773, 475643, 218117]
list:  [   166    176    130    187    127    132    128    177    152    163
      5      4      5      2      2      3      4      3      3      4
 628457 506601 692374 240345 566213 248244 682854 671773 475643 218117]


2. & 3.

In [84]:
l = np.reshape(l, (3, 10))
l = l.transpose()
print(l.shape)
print('| size | rooms | price |')
print(l)


(10, 3)
| size | rooms | price |
[[   169      4 415459]
 [   126      2 716520]
 [   177      3 630795]
 [   171      2 439207]
 [   185      3 441776]
 [   127      4 611276]
 [   182      3 415176]
 [   125      4 678025]
 [   156      2 523271]
 [   192      2 324186]]


4.

In [18]:
#Load the Earthquakes dataset. Export the dataset to an array as you covered in the previous lesson.
import pandas as pd
df = pd.read_csv('earthquakes1970-2014.csv')
print(df.shape)
print(df.head())


(5304, 12)
                 DateTime  Latitude  Longitude  Depth  Magnitude MagType  \
0  1970/01/04 17:00:40.20    24.139    102.503   31.0        7.5      Ms   
1  1970/01/06 05:35:51.80    -9.628    151.458    8.0        6.2      Ms   
2  1970/01/08 17:12:39.10   -34.741    178.568  179.0        6.1      Mb   
3  1970/01/10 12:07:08.60     6.825    126.737   73.0        6.1      Mb   
4  1970/01/16 08:05:39.00    60.280   -152.660   85.0        6.0      ML   

   NbStations  Gap  Distance  RMS Source       EventID  
0        90.0  NaN       NaN  0.0    NEI  1.970010e+09  
1        85.0  NaN       NaN  0.0    NEI  1.970011e+09  
2        59.0  NaN       NaN  0.0    NEI  1.970011e+09  
3        91.0  NaN       NaN  0.0    NEI  1.970011e+09  
4         0.0  NaN       NaN  NaN     AK           NaN  


5.

In [19]:
#Slice first 20 rows and column numbers 3, 5, 6, 7, 12. Then, assign the array you sliced to a variable.

df_sliced = df.iloc[:20,[2,4,5,6,11]]
print(df_sliced)

    Longitude  Magnitude MagType  NbStations       EventID
0    102.5030        7.5      Ms        90.0  1.970010e+09
1    151.4580        6.2      Ms        85.0  1.970011e+09
2    178.5680        6.1      Mb        59.0  1.970011e+09
3    126.7370        6.1      Mb        91.0  1.970011e+09
4   -152.6600        6.0      ML         0.0           NaN
5   -177.3490        6.5      Mb       175.0  1.970012e+09
6    142.9660        6.4      Ms       199.0  1.970012e+09
7   -104.2980        6.6      Ms       140.0  1.970012e+09
8    166.3700        6.4      Ms        91.0  1.970013e+09
9    -99.4840        6.5      Ms       100.0  1.970020e+09
10   122.1170        6.6      Ms        94.0  1.970021e+09
11   100.7750        6.1      Ms        57.0  1.970021e+09
12   103.0310        6.0      Ms        94.0  1.970022e+09
13  -179.5898        6.0      ML         0.0           NaN
14  -175.0400        6.1      ML         0.0           NaN
15   143.7070        6.2      Ms        82.0  1.970030e+

6.


In [20]:
#Display the row numbers Magnitude where last values are equal to 4.5 or higher. 
# Taking Magnitude to first column
df_sliced = df_sliced[['Magnitude','Longitude','MagType','NbStations','EventID']]
print(df_sliced[df_sliced['Magnitude'] >= 4.5])

# sort by Magnitude
# df_sliced = df_sliced.sort_values(by=['Magnitude'], ascending=False)
# print(df_sliced)



    Magnitude  Longitude MagType  NbStations       EventID
0         7.5   102.5030      Ms        90.0  1.970010e+09
1         6.2   151.4580      Ms        85.0  1.970011e+09
2         6.1   178.5680      Mb        59.0  1.970011e+09
3         6.1   126.7370      Mb        91.0  1.970011e+09
4         6.0  -152.6600      ML         0.0           NaN
5         6.5  -177.3490      Mb       175.0  1.970012e+09
6         6.4   142.9660      Ms       199.0  1.970012e+09
7         6.6  -104.2980      Ms       140.0  1.970012e+09
8         6.4   166.3700      Ms        91.0  1.970013e+09
9         6.5   -99.4840      Ms       100.0  1.970020e+09
10        6.6   122.1170      Ms        94.0  1.970021e+09
11        6.1   100.7750      Ms        57.0  1.970021e+09
12        6.0   103.0310      Ms        94.0  1.970022e+09
13        6.0  -179.5898      ML         0.0           NaN
14        6.1  -175.0400      ML         0.0           NaN
15        6.2   143.7070      Ms        82.0  1.970030e+

7.


In [32]:
#Assign 1 to first row
df_sliced[df_sliced.index==0] = 1
print(df_sliced)
print(df_sliced.shape)

    Magnitude  Longitude MagType  NbStations       EventID
0         1.0     1.0000       1         1.0  1.000000e+00
1         6.2   151.4580      Ms        85.0  1.970011e+09
2         6.1   178.5680      Mb        59.0  1.970011e+09
3         6.1   126.7370      Mb        91.0  1.970011e+09
4         6.0  -152.6600      ML         0.0           NaN
5         6.5  -177.3490      Mb       175.0  1.970012e+09
6         6.4   142.9660      Ms       199.0  1.970012e+09
7         6.6  -104.2980      Ms       140.0  1.970012e+09
8         6.4   166.3700      Ms        91.0  1.970013e+09
9         6.5   -99.4840      Ms       100.0  1.970020e+09
10        6.6   122.1170      Ms        94.0  1.970021e+09
11        6.1   100.7750      Ms        57.0  1.970021e+09
12        6.0   103.0310      Ms        94.0  1.970022e+09
13        6.0  -179.5898      ML         0.0           NaN
14        6.1  -175.0400      ML         0.0           NaN
15        6.2   143.7070      Ms        82.0  1.970030e+

In [43]:
# Save the final state of the array to disk. You are going to use this in the next assignment.
df_sliced.to_csv('earthquakes1970-2014_sliced.csv', index=False)

In [103]:
# Load the array you saved in the previous lesson from the disk.
df_sliced_new = pd.read_csv('earthquakes1970-2014_sliced.csv')
df_sliced_new.head()



Magnitude  Longitude MagType  NbStations       EventID
0        1.0      1.000       1         1.0  1.000000e+00
1        6.2    151.458      Ms        85.0  1.970011e+09
2        6.1    178.568      Mb        59.0  1.970011e+09
3        6.1    126.737      Mb        91.0  1.970011e+09
4        6.0   -152.660      ML         0.0           NaN

In [104]:
# Display the mean and the standard deviation for each column.
df_sliced_new.mean(skipna=True, numeric_only=True) # mean




Magnitude     5.990000e+00
Longitude     2.211561e+01
NbStations    7.560000e+01
EventID       1.846893e+09
dtype: float64

In [105]:
df_sliced_new.std(skipna=True, numeric_only=True) # std

Magnitude     1.195562e+00
Longitude     1.419991e+02
NbStations    5.726338e+01
EventID       4.925048e+08
dtype: float64

In [106]:
#types
df_sliced_new.dtypes

Magnitude     float64
Longitude     float64
MagType        object
NbStations    float64
EventID       float64
dtype: object

In [107]:
# describe
df_sliced_new.describe()

Magnitude   Longitude  NbStations       EventID
count  20.000000   20.000000    20.00000  1.600000e+01
mean    5.990000   22.115610    75.60000  1.846893e+09
std     1.195562  141.999134    57.26338  4.925048e+08
min     1.000000 -179.589800     0.00000  1.000000e+00
25%     6.000000 -116.388500    43.00000  1.970012e+09
50%     6.150000  101.903000    83.50000  1.970017e+09
75%     6.500000  144.997750    95.50000  1.970024e+09
max     6.600000  178.568000   199.00000  1.970032e+09

In [108]:
# columns
df_sliced_new.columns

Index(['Magnitude', 'Longitude', 'MagType', 'NbStations', 'EventID'], dtype='object')

In [109]:
# dropping MagType
df_sliced_new = df_sliced_new.drop(['MagType'], axis=1)

In [110]:
# columns
df_sliced_new.columns

Index(['Magnitude', 'Longitude', 'NbStations', 'EventID'], dtype='object')

In [111]:
#types
df_sliced_new.dtypes

Magnitude     float64
Longitude     float64
NbStations    float64
EventID       float64
dtype: object

In [112]:
# Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be dobe in one line of code.)

df_sliced_new = df_sliced_new.select_dtypes(include=None, exclude=object) - np.array([1, 25, 10, 4])
df_sliced_new


Magnitude  Longitude  NbStations       EventID
0         0.0   -24.0000        -9.0 -3.000000e+00
1         5.2   126.4580        75.0  1.970011e+09
2         5.1   153.5680        49.0  1.970011e+09
3         5.1   101.7370        81.0  1.970011e+09
4         5.0  -177.6600       -10.0           NaN
5         5.5  -202.3490       165.0  1.970012e+09
6         5.4   117.9660       189.0  1.970012e+09
7         5.6  -129.2980       130.0  1.970012e+09
8         5.4   141.3700        81.0  1.970013e+09
9         5.5  -124.4840        90.0  1.970020e+09
10        5.6    97.1170        84.0  1.970021e+09
11        5.1    75.7750        47.0  1.970021e+09
12        5.0    78.0310        84.0  1.970022e+09
13        5.0  -204.5898       -10.0           NaN
14        5.1  -200.0400       -10.0           NaN
15        5.2   118.7070        72.0  1.970030e+09
16        5.5   143.6030        51.0  1.970031e+09
17        5.0   123.8700        55.0  1.970031e+09
18        5.5  -178.9700       -10.0           NaN
19        5.0   -94.4990       108.0  1.970032e+09

In [113]:
# Multiply each element by 2. (Remember it can be done in one line of code.)
df_sliced_new = df_sliced_new * 2
df_sliced_new


Magnitude  Longitude  NbStations       EventID
0         0.0   -48.0000       -18.0 -6.000000e+00
1        10.4   252.9160       150.0  3.940021e+09
2        10.2   307.1360        98.0  3.940022e+09
3        10.2   203.4740       162.0  3.940022e+09
4        10.0  -355.3200       -20.0           NaN
5        11.0  -404.6980       330.0  3.940024e+09
6        10.8   235.9320       378.0  3.940024e+09
7        11.2  -258.5960       260.0  3.940024e+09
8        10.8   282.7400       162.0  3.940025e+09
9        11.0  -248.9680       180.0  3.940041e+09
10       11.2   194.2340       168.0  3.940041e+09
11       10.2   151.5500        94.0  3.940041e+09
12       10.0   156.0620       168.0  3.940045e+09
13       10.0  -409.1796       -20.0           NaN
14       10.2  -400.0800       -20.0           NaN
15       10.4   237.4140       144.0  3.940061e+09
16       11.0   287.2060       102.0  3.940062e+09
17       10.0   247.7400       110.0  3.940062e+09
18       11.0  -357.9400       -20.0           NaN
19       10.0  -188.9980       216.0  3.940063e+09