In [1]:
import numpy as np
print(np.__version__)

1.20.3


# 1


1. Write a NumPy program to convert a list of numeric value into a one-dimensional NumPy array.

In [2]:
alist = [12.23, 13.32, 100, 36.32]
print(alist)
arraylist = np.array(alist)
print(arraylist)

arraylist.shape

[12.23, 13.32, 100, 36.32]
[ 12.23  13.32 100.    36.32]


(4,)

# 2

2. Write a NumPy program to create a 3x3 matrix with values ranging from 2 to 10.


In [3]:
numberlist = np.arange(2,11).reshape([3,3])
print(numberlist)


[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


# 3

3. Write a NumPy program to create a null vector of size 10 and update sixth value to 11.

In [4]:
arrzeros = np.zeros(10)
print(arrzeros)
arrzeros[5]=11
print(arrzeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.  0.  0.  0.  0. 11.  0.  0.  0.  0.]


# 4


4. Write a NumPy program to create an array with values ranging from 12 to 38.

In [5]:
rangeexample = np.arange(12,38)
print(rangeexample)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37]


# 5


5. Write a NumPy program to reverse an array (first element becomes last).

In [6]:
orgarray = np.arange(12,21)
print(orgarray)
revarray = orgarray[::-1]
print(revarray)

[12 13 14 15 16 17 18 19 20]
[20 19 18 17 16 15 14 13 12]


# 6

6. Write a NumPy program to convert an array to a float type.

In [7]:
orgarray = [1, 2, 3, 4]
orgarray = np.array(orgarray)
print(orgarray)
convarray = np.asfarray(orgarray)
print(convarray)

[1 2 3 4]
[1. 2. 3. 4.]


# 7

7. Write a NumPy program to create a 2d array with 1 on the border and 0 inside.

In [8]:
arrayex = np.ones((5,5))
print(arrayex)
arraynew = arrayex[1:-1, 1:-1]
print(arraynew)
arrayex[1:-1, 1:-1]=0
print(arrayex)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# 8

8. Write a NumPy program to add a border (filled with 0's) around an existing array.

In [9]:
myarray = np.ones((3,3))
print(myarray)
myarray2 = np.zeros((myarray.shape[0]+2, myarray.shape[1]+2))
print(myarray2)
myarray2[1:-1, 1:-1]=myarray
print(myarray2)

#with pad
x = np.ones((3,3))
print(x)
z = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(z)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 9

9. Write a NumPy program to create a 8x8 matrix and fill it with a checkerboard pattern.

In [10]:
myarray = np.zeros((8,8))
myarray[1::2, ::2]=1
myarray[::2, 1::2]=1
print(myarray)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 10

10. Write a NumPy program to convert a list and tuple into arrays.

In [11]:
mylist = [1, 2, 3, 4, 5, 6, 7, 8]
np.asarray(mylist)
print(mylist)
mytuple= ([8, 4, 6], [1, 2, 3])
print(mytuple)
np.asarray(mytuple)

[1, 2, 3, 4, 5, 6, 7, 8]
([8, 4, 6], [1, 2, 3])


array([[8, 4, 6],
       [1, 2, 3]])

# 11

11. Write a NumPy program to append values to the end of an array.

In [12]:
mylist = [10, 20, 30]
origarray = np.array(mylist)
print(origarray)
neworigarray = np.append(mylist, [[40, 50, 60], [70, 80, 90]])
print(neworigarray)

[10 20 30]
[10 20 30 40 50 60 70 80 90]


# 12

12.Write a NumPy program to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [13]:
faharray = [0, 12, 45.21 ,34, 99.91]
faharray = np.array(faharray)
print(faharray)
centarray = [(5*(faharray[0]-32))/9, (5*(faharray[1]-32))/9, (5*(faharray[2]-32))/9, (5*(faharray[3]-32))/9,(5*(faharray[4]-32))/9 ]
centarray = np.array(centarray)
print(centarray)

[ 0.   12.   45.21 34.   99.91]
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


# 13

13.Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements

In [14]:
x = [1, 2, 3]

x = np.array(x)
print(x.size)
print(x.itemsize)
print(x.nbytes)


3
8
24


# 14

14. Write a NumPy program to find common values between two arrays.

In [15]:
array1 = [0, 10, 20, 40, 60]
array2 = [10, 30, 40]
array1 = np.array(array1)
array2 = np.array(array2)
print('Array1: ', array1)
print('Array2: ', array2)
print('Common values between two arrays: ')
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10 30 40]
Common values between two arrays: 
[10 40]


# 15

15. Write a NumPy program to get the unique elements of an array.

In [16]:
originalarray = np.array([10, 10, 20, 20, 30, 30])
print('Original array: ', originalarray)
print('Unique elements of the above array: ')
print(np.unique(originalarray))
originalarray = np.array([[1, 1], [2, 3]])
print('Original array:\n', originalarray)
print('Unique elements of the above array: ')
print(np.unique(originalarray))


Original array:  [10 10 20 20 30 30]
Unique elements of the above array: 
[10 20 30]
Original array:
 [[1 1]
 [2 3]]
Unique elements of the above array: 
[1 2 3]


# 16

16. Write a NumPy program to find the set difference of two arrays. The set difference will return the sorted, unique values in array1 that are not in array2.


In [17]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print('Array1: ',array1)
array2 = [10, 30, 40, 50, 70]
print('Array2: ',array2)
print('Unique values in array1 that are not in array2: ')
print(np.setdiff1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values in array1 that are not in array2: 
[ 0 20 60 80]


# 17

17. Write a NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays.


In [18]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print("Array1: ", array1)
array2 = [10, 30, 40, 50, 70]
print("Array2: ", array2)
print("Unique values that are in only one (not both) of the input arrays: ")
print(np.setxor1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10, 30, 40, 50, 70]
Unique values that are in only one (not both) of the input arrays: 
[ 0 20 30 50 60 70 80]


# 18

18. Write a NumPy program to find the union of two arrays. Union will return the unique, sorted array of values that are in either of the two input arrays.

In [19]:
array1 = np.array([0, 10, 20, 40, 60, 80])
print('Array1: ', array1)
array2 = np.array([10, 30, 40, 50, 70])
print('Array2: ', array2)
print('Unique sorted array of values that are in either of the two input array s: ')
print(np.union1d(array1, array2))

Array1:  [ 0 10 20 40 60 80]
Array2:  [10 30 40 50 70]
Unique sorted array of values that are in either of the two input array s: 
[ 0 10 20 30 40 50 60 70 80]


# 19

19. Write a NumPy program to test whether all elements in an array evaluate to True. Note: 0 evaluates to False in python.

In [20]:
print(np.all([[True,False],[True,True]]))
print(np.all([[True,True],[True,True]]))
print(np.all([10, 20, 0, -50]))
print(np.all([10, 20, -50]))

False
True
False
True


# 20

20. Write a NumPy program to find the indices of the maximum and minimum values along the given axis of an array.

In [21]:
originalarray = np.array([1, 2, 3, 4, 5,6])
print('Original array: ', originalarray)
print('Maximum Values: ',np.argmax(originalarray))
print('Minimum Values: ',np.argmin(originalarray))

Original array:  [1 2 3 4 5 6]
Maximum Values:  5
Minimum Values:  0


# 21

21. Write a NumPy program to get the values and indices of the elements that are bigger than 10 in a given array.

In [22]:
orgarray = np.array([[0, 10, 20], [20, 30, 40]])
print('Original array: \n', orgarray)
print('Bigger than 10 =', orgarray[orgarray > 10])
print('Indices are ', np.nonzero(orgarray > 10))


Original array: 
 [[ 0 10 20]
 [20 30 40]]
Bigger than 10 = [20 20 30 40]
Indices are  (array([0, 1, 1, 1]), array([2, 0, 1, 2]))


# 22

22. Write a NumPy program to create an array of ones of size 2 and an array of zeros of size 2.

In [23]:
arrayzeros = np.zeros((1,2))
arrayones = np.ones((1,2))
print("Zeros:", arrayzeros)
print("Ones:", arrayones)

Zeros: [[0. 0.]]
Ones: [[1. 1.]]


# 23

23. Write a NumPy program to create a contiguous flattened array.

In [24]:
x = np.array([[10, 20, 30], [20, 40, 50]])
print('Original array:\n', x)
print('New flattened array: ', np.ravel(x))

Original array:
 [[10 20 30]
 [20 40 50]]
New flattened array:  [10 20 30 20 40 50]


# 24

24. Write a NumPy program to create a new shape to an array without changing its data.

In [25]:
x = np.array([1, 2, 3, 4, 5, 6])
x = np.reshape(x,(3,2))
print('Reshape 3x2:\n', x)
x = np.reshape(x,(2,3))
print('Reshape 2x3:\n', x)

Reshape 3x2:
 [[1 2]
 [3 4]
 [5 6]]
Reshape 2x3:
 [[1 2 3]
 [4 5 6]]


# 25

25. Write a NumPy program to change the data type of an array.

In [26]:
x = np.array([[2, 4, 6], [6, 8, 10]])
print(x)
print('Data type of the array x is: ', x.dtype)
x = x.astype('float64')
print('New Type: ', x.dtype)
print(x)

[[ 2  4  6]
 [ 6  8 10]]
Data type of the array x is:  int64
New Type:  float64
[[ 2.  4.  6.]
 [ 6.  8. 10.]]


# 26

26. Write a NumPy program to create a 1-D array of 20 element spaced evenly on a log scale between 2. and 5., exclusive.

In [27]:
array =  np.logspace(2., 5., 20, endpoint=False)
print(array)

[  100.           141.25375446   199.5262315    281.83829313
   398.10717055   562.34132519   794.32823472  1122.0184543
  1584.89319246  2238.72113857  3162.27766017  4466.83592151
  6309.5734448   8912.50938134 12589.25411794 17782.79410039
 25118.8643151  35481.33892336 50118.72336273 70794.57843841]


# 27

27. Write a NumPy program to concatenate two 2-dimensional arrays. Sample arrays: ([[0, 1, 3], [5, 7, 9]], [[0, 2, 4], [6, 8, 10]]

In [28]:
a = np.array([[0, 1, 3], [5, 7, 9]])
b = np.array([[0, 2, 4], [6, 8, 10]])
x = np.concatenate((a, b), 1)
print(x)

[[ 0  1  3  0  2  4]
 [ 5  7  9  6  8 10]]


# 28

28. Write a Python program to split an array of 14 elements into 3 arrays, each of which has 2, 4, and 8 elements in the original order. Sample array: [ 1 2 3 4 5 6 7 8 9 10 11 12 13 14]

In [29]:
originalarray = np.arange(1, 15)
print('Original array: ', originalarray)
originalarray = np.split(originalarray, [2,6])
print('After splitting: \n', originalarray)

Original array:  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
After splitting: 
 [array([1, 2]), array([3, 4, 5, 6]), array([ 7,  8,  9, 10, 11, 12, 13, 14])]


# 29

29. Write a NumPy program to split of an array of shape 4x4 it into two arrays along the second axis. Sample array : [[ 0 1 2 3] [ 4 5 6 7] [ 8 9 10 11] [12 13 14 15]]

In [30]:
sample = np.arange(0,16)
sample = sample.reshape((4, 4))
print('Sample array:\n', sample)
sample = np.hsplit(sample, [2,6])
print('After splitting horizontally:\n', sample)

Sample array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
After splitting horizontally:
 [array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]]), array([], shape=(4, 0), dtype=int64)]


# 30

30. Write a NumPy program to get the number of nonzero elements in an array. Original array:

In [31]:
origarray = np.array([[0, 10, 20], [20, 30, 40]])
print('Original array:\n', origarray)
origarray = np.count_nonzero(origarray)
print('Number of non zero elements in the above array:\n', origarray)

Original array:
 [[ 0 10 20]
 [20 30 40]]
Number of non zero elements in the above array:
 5


# 31

31. Write a NumPy program to add an extra column to a NumPy array.

In [32]:
x = np.array([[10, 20, 30], [40, 50, 60]])
y = np.array([[100],[200]])
z = np.append(x, y, axis=1)
print(z)

[[ 10  20  30 100]
 [ 40  50  60 200]]


# 32

32.Write a NumPy program to remove the negative values in a NumPy array with 0.

In [33]:
sample = np.array([-1, -4, 0, 2, 3, 4, 5, -6])
print(sample)
sample[sample < 0] = 0
print(sample)

[-1 -4  0  2  3  4  5 -6]
[0 0 0 2 3 4 5 0]


# 33

33. Write a NumPy program to remove all rows in a NumPy array that contain non-numeric values.

In [34]:
arr = np.array([[1,2,3], [4,5,np.nan], [7,8,9], [True, False, True]])
print('Array: \n', arr)
arr = arr[~np.isnan(arr).any(axis=1)]
print('After remove:\n', arr)

Array: 
 [[ 1.  2.  3.]
 [ 4.  5. nan]
 [ 7.  8.  9.]
 [ 1.  0.  1.]]
After remove:
 [[1. 2. 3.]
 [7. 8. 9.]
 [1. 0. 1.]]


# 34

34. Write a NumPy program to select indices satisfying multiple conditions in a NumPy array.

In [35]:
a = np.array([97, 101, 105, 111, 117])
b = np.array(['a','e','i','o','u'])
print(a)
print(b)
print(b[(100 < a) & (a < 110)])

[ 97 101 105 111 117]
['a' 'e' 'i' 'o' 'u']
['e' 'i']


# 35

35. Write a NumPy program to count the frequency of unique values in numpy array.

In [36]:
arr = np.array([10, 10, 20, 10, 20, 20, 20, 30, 30, 50, 40, 40])
print(arr)
unique, counts = np.unique(arr, return_counts = True)
print('Frequency of unique values of the array:\n', np.array((unique, counts)))

[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the array:
 [[10 20 30 40 50]
 [ 3  4  2  2  1]]


# 36

36. Write a NumPy program to access last two columns of a multidimensional columns.


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr)
x = arr[:,[1,2]]
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]
 [8 9]]


# 37

37. Write a NumPy program to find indices of elements equal to zero in a NumPy array.

In [38]:
arr = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])
print('Original array: ', arr)
print("Indices of elements equal to zero: ", np.where(arr == 0)[0])

Original array:  [1 0 2 0 3 0 4 5 6 7 8]
Indices of elements equal to zero:  [1 3 5]
